### ISSUE TITLE
Afterglow fails to launch on headless devices.

### ISSUE THREAD

**Issue by Busti** [Deep-Symmetry/afterglow#65]
Hi,
I am trying to start afterglow on a headless raspberry pi and it fails with the following error message:

```
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at clojure.java.browse_ui$open_url_in_swing.invokeStatic(browse_ui.clj:19)
        at clojure.java.browse_ui$open_url_in_swing.invoke(browse_ui.clj:15)
        at clojure.lang.Var.invoke(Var.java:379)
        at clojure.java.browse$open_url_in_swing.invokeStatic(browse.clj:64)
        at clojure.java.browse$browse_url.invokeStatic(browse.clj:74)
        at clojure.java.browse$browse_url.invoke(browse.clj:66)
        at afterglow.core$start_web_server.invokeStatic(core.clj:219)
        at afterglow.core$start_web_server.invoke(core.clj:202)
        at afterglow.core$_main.invokeStatic(core.clj:296)
        at afterglow.core$_main.doInvoke(core.clj:260)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at afterglow.core.main(Unknown Source)
```

**Comment by brunchboy** [comment]
It looks like you are trying to run it using `java -jar`, which currently assumes that you want to open a web browser window in order to interact with afterglow, since you aren’t starting things from a Clojure REPL. That will not work in a headless environment.

As a temporary workaround, you can change [this line](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/core.clj#L299) to omit the `true` argument, or replace it with `false`. When I have a moment, I will add a new command-line argument to suppress this behavior.

However, given other reports I have heard, the memory and processor resources of a Raspberry Pi may not be adequate for a high-performance Java application like afterglow.

**Comment by brunchboy** [comment]
Ok, I have used this as a reason to put together a new release. If you download [version 0.2.4](https://github.com/brunchboy/afterglow/releases/tag/v0.2.4), there is a new command-line argument that should prevent this crash.

    java -jar afterglow.jar -n

The `-n` (or `--no-browser`) argument tells afterglow to not try to launch a local web browser window to show its web interface. You can still connect to it remotely from another machine, of course.

Please let me know if this lets you get farther, and how you find performance to be on the Pi. I would also love to know what you are experimenting with, and would be happy to help you create lighting fixture definitions if you need any.

**Comment by Busti** [comment]
Hey,  
thanks for responding so quickly.  

I am trying to use a raspberry PI Zero W as the main platform for an event coming up in may. I already compiled OLA to be able to use the gpio pins of the PI to drive WS2812 Strips.
We are also going to rent some Futurelight PHS 260 Moving heads and I would love to supply fixture definitions for those and anything else we may rent for this and upcoming events.  

After your latest release I can start up the jar on the PI and the performance seems to be good.  
I am currently trying to get into clojure and trying to setup the init file for the show. I am usually working with scala and wasn't able to wrap my head around it just yet, but I am getting there.

**Comment by brunchboy** [comment]
That’s excellent! I love people exploring new ways of using this system after I poured so many hours into designing and building it, so I am happy to answer any questions you may have. I see that QLC+ has added a fixture definition for the Futurelight PHS 260, so we can use that as a starting point, but I also notice that they have changed the XML schema they use, so Afterglow’s built in QXF converter has stopped working. I am investigating how to fix that now, and will share the converted fixture definition once I have succeeded.

And yes, if Clojure is your first Lisp, it takes a while to wrap your head around it, but starting from scala will give you a head start over most people, and I have good reason to hope you will end up liking it too.

**Comment by brunchboy** [comment]
All right, it was easy to add support for their new XML schema URL, so here is the auto-translated fixture definition. Since I don’t have one of the lights to work with, I am unable to figure out the proper values for `:pan-center`, `:pan-half-circle`, `:tilt-center`, and `:tilt-half-circle`. If you can work those out, and test this, I would greatly appreciate it.
[futurelight-phs-260.clj.zip](https://github.com/brunchboy/afterglow/files/950010/futurelight-phs-260.clj.zip)

**Comment by Busti** [comment]
Thank you,  
I will measure the values as soon as we rent the fixtures next weekend.
