### ISSUE TITLE
Sync with CDJ 2000 NX2

### ISSUE THREAD

**Issue by hottehead** [Deep-Symmetry/afterglow#77]
**Describe the bug**
The player is found when I press "sync" in the web UI. After pressing sync the manual slider disappears. However the bpm value does not change to the current player bpm, neither does it change if the slider on the player is moved.

**To Reproduce**
UI
1. Use sample-show from examples namespace
2. Go to any show
3. Click on sync and select a player listed there
4. Look at bpm value beloew
5. BPM value is not equal to the player bpm

Code
```
(afterglow.dj-link/current-dj-link-sources)
=> #{{:name "CDJ-2000NXS2", :player 2, :address #object[java.net.Inet4Address 0x1ee3a5fa "/192.168.0.178"]}}
(show/sync-to-external-clock
  (afterglow.dj-link/sync-to-dj-link "CDJ-2000NXS2"))
=>
#afterglow.dj_link.UDPSync{:metronome #afterglow.rhythm.Metronome{:start #object[clojure.lang.Ref
                                                                                 0x4244b5a0
                                                                                 {:status :ready, :val 1723477534154}],
                                                                  :bpm #object[clojure.lang.Ref
                                                                               0x70575a57
                                                                               {:status :ready, :val 120}],
                                                                  :bpb #object[clojure.lang.Ref
                                                                               0x1d79a8d6
                                                                               {:status :ready, :val 4}],
                                                                  :bpp #object[clojure.lang.Ref
                                                                               0x110fc8f9
                                                                               {:status :ready, :val 8}]},
                           :source {:name "CDJ-2000NXS2",
                                    :player 2,
                                    :address #object[java.net.Inet4Address 0x1ee3a5fa "/192.168.0.178"]},
                           :sync-count #object[clojure.lang.Ref 0x602212ee {:status :ready, :val 0}],
                           :level :beat}
(show/sync-status)
=>
{:type :dj-link,
 :current false,
 :level :beat,
 :source {:name "CDJ-2000NXS2", :player 2, :address #object[java.net.Inet4Address 0x1ee3a5fa "/192.168.0.178"]},
 :status "Not playing? No DJ Link beats received from CDJ-2000NXS2."}
```

**Expected behavior**
BPM updates in WebUI and internally checked with `(afterglow.rhythm/metro-bpm (:metronome *show*) 130)`

**Screenshots**
![Bildschirmfoto 2024-08-12 um 17 27 58](https://github.com/user-attachments/assets/6fd70fb9-c037-45f7-b4da-174e512d2ed2)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi 4
 - afterglow  `0.2.5`

**Additional context**
The beat link trigger tool shows me the correct infromation about the player. I assume it should work.

<img width="1329" alt="Bildschirmfoto 2024-08-12 um 17 38 29" src="https://github.com/user-attachments/assets/f93b2195-a2b7-4dfe-bc07-36d61390efaf">

**Comment by brunchboy** [comment]
Hello! It’s delightful to hear that someone is actually using Afterglow. I will try to find some time to reproduce this, although I don’t have any nxs2 players, hopefully a CDJ-3000 would work. But in the mean time, I would suggest trying to run and/or build Afterglow with a much more recent release of beat-link. It looks like afterglow 0.2.5 is using beat-link 0.6.3, and the current development beat-link builds are 8.0.0-SNAPSHOT. There have been a [ton of fixes and improvements](https://github.com/Deep-Symmetry/beat-link/blob/main/CHANGELOG.md) in the years since 0.6.3 was released.

**Comment by brunchboy** [comment]
(I have not been cutting Afterglow releases because I haven’t been hearing from anyone using it, while I hear from tons of people using Beat Link Trigger, which is not surprising because the latter is far more approachable, especially to non-developers. But we should hopefully be able to get you straightened out this week, now that you have chimed in. 😄)

**Comment by brunchboy** [comment]
To let you try things more quickly (although I definitely encourage you to get set up to run from source, and make your own build jars), I have updated the preview build on GitHub. It took a bit longer because it turns out that Blizzard has taken down some of the pages about fixtures that the API docs link to, so the link checker in the Github Actions build script failed my first attempt.

I have updated many of the dependencies, including Beat Link. See if [this preview jar](https://github.com/Deep-Symmetry/afterglow/releases/tag/v0.2.6-SNAPSHOT) works any better for you.

**Comment by hottehead** [comment]
Well, I am delighted that you made this tool. I've written a similar proof of concept with the same core idea of a oscillating, beat synchronized show last year and ran a small show with it. And even though it was flawed it made for a good show. Then I found afterglow via the question on how to synchronize the tool with CDJs. And well, you already solved the tasks I had on my sheet, and using a live coding env is a great idea. So here I am, learning afterglow and clojure 😅


This 0.2.6 snapshot works. If I understand correctly you built 0.2.6 using the dependencies from this commit https://github.com/Deep-Symmetry/afterglow/commit/00eebdb7a7e00cf18ebf8d7873f2fa0af3bdd8ea
And if I read the git log correctly 0.2.6 differs from 0.2.5 only in 1 commit. So I can safely replace it without having to rewrite anything in my show?

I also built an uberjar from the current main branch. It works too. This was my first ever clojure build 🥳

Thanks a lot for the quick response.

**Comment by hottehead** [comment]
tested with my current show and seems to work so far. 
closing this issue. I may ask a thing or two in the zulip chat this week. 😁

**Comment by brunchboy** [comment]
Thanks for letting me know, and congratulations on leveling up in building Clojure! And, though I said this over in Zulip, for anyone else reading this in the future: the latest preview should be backwards compatible with the version you were using before, it mostly contains dependency updates and a few build and link fixes, but it is great to hear feedback from someone actually testing it.
